### PR TITLE
2020 Updates

### PR DESCRIPTION
**Pull request by kwelch**

### CODE REVIEW

**Comment by itzsaga** [comment]
Can Netlify do subdomains? My thinking is archived years aren't "year controlled". So if say the CoC updates in 2020 then the 2019 will still link to the current CoC. With a more complete site preserved there's more info for reference. Like, if someone liked the food and wanted to go see who catered that's not possible now. I don't think it should hold this up at all but maybe a consideration moving forward. Keep the single page but move to subdomains like other conferences. e.g. [PyTennessee](https://2020.pytennessee.org/).

My other comment is that the footer has some odd alignment but it's not a blocker IMO.
Screen Shot 2020-01-15 at 07 11 49
The content of the three columns should be Left, Center, Right aligned respectively IMO. I'll just open an issue on this one.

**Comment by kwelch** [comment]
I like the idea of domains, for this first pass I was shooting for simplicity. I think even if the CoC changed, we should only have it listed once. I don't see a large need for an archived CoC based on the year, but I could be persuaded.

**Comment by kwelch** [comment]
An upside of archiving as domain, we could split the years by repo and deploy via domain. That would open it up to the possibility of create a new site each year and easier way of migrating to new tech.

**Comment by itzsaga** [comment]
I didn't think about separate repos but that would be a nice feature. I was more thinking folders but the build gets more complex if it goes a monorepo type of structure with different dependencies based on folder. I also don't know if Netlify can map a repo folder to specific deployments.

**Review by itzsaga — APPROVED** [review]

**Pull request merged**
